"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { Navigation } from "@/components/molecules/navigation";
import { JazzAndAuth } from "@/components/jazz-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Theme>
					<JazzAndAuth>
						<div className="min-h-screen bg-gray-50">
							<Navigation />
							<main>{children}</main>
						</div>
					</JazzAndAuth>
				</Theme>
			</body>
		</html>
	);
}
