name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: ./frontend/package.json

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: gardencmp
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: yarn Build
      run: |
        yarn install
        yarn build;
      working-directory: ./frontend

    - name: Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/gardencmp/succulent-frontend:${{github.head_ref || github.ref_name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: gardencmp
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ghcr.io/gardencmp/succulent-backend:${{github.head_ref || github.ref_name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: gacts/install-nomad@v1
    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Deploy on Nomad
      run: |
        if [ "${{github.ref_name}}" == "main" ]; then
          export BRANCH_SUFFIX="";
          export BRANCH_SUBDOMAIN="";
        else
          export BRANCH_SUFFIX=-${{github.head_ref || github.ref_name}};
          export BRANCH_SUBDOMAIN=${{github.head_ref || github.ref_name}}.;
        fi

        export DOCKER_USER=gardencmp;
        export DOCKER_PASSWORD=${{ secrets.DOCKER_PULL_PAT }};
        export DOCKER_TAG=ghcr.io/gardencmp/succulent-frontend:${{github.head_ref || github.ref_name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}};

        envsubst '${DOCKER_USER} ${DOCKER_PASSWORD} ${DOCKER_TAG} ${BRANCH_SUFFIX} ${BRANCH_SUBDOMAIN}' < job-template.nomad > job-instance.nomad;
        cat job-instance.nomad;
        NOMAD_ADDR=${{ secrets.NOMAD_ADDR }} nomad job run job-instance.nomad;
      working-directory: ./frontend

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: gacts/install-nomad@v1
    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Deploy on Nomad
      run: |
        if [ "${{github.ref_name}}" == "main" ]; then
          export BRANCH_SUFFIX="";
          export BRANCH_SUBDOMAIN="";
        else
          export BRANCH_SUFFIX=-${{github.head_ref || github.ref_name}};
          export BRANCH_SUBDOMAIN=${{github.head_ref || github.ref_name}}.;
        fi

        export DOCKER_USER=gardencmp;
        export DOCKER_PASSWORD=${{ secrets.DOCKER_PULL_PAT }};
        export DOCKER_TAG=ghcr.io/gardencmp/succulent-backend:${{github.head_ref || github.ref_name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}};

        envsubst '${DOCKER_USER} ${DOCKER_PASSWORD} ${DOCKER_TAG} ${BRANCH_SUFFIX} ${BRANCH_SUBDOMAIN}' < job-template.nomad > job-instance.nomad;
        cat job-instance.nomad;
        NOMAD_ADDR=${{ secrets.NOMAD_ADDR }} nomad job run job-instance.nomad;
      working-directory: ./backend