name: Build and Deploy

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    outputs:
      modified-branch-name: ${{ steps.env.outputs.MODIFIED_BRANCH_NAME }}
    name: env-job
    steps:
      - name: Sets MODIFIED_BRANCH_NAME
        id: env
        env:
          name: '${{env.BRANCH_NAME}}'
        run: |
          echo "MODIFIED_BRANCH_NAME=${name/\//-}" >> ${GITHUB_OUTPUT}

  build-frontend:
    runs-on: ubuntu-latest
    needs:
      - env-job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: ./frontend/package.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gardencmp
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: yarn Build
        run: |
          yarn install
          yarn build;
        working-directory: ./frontend

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/gardencmp/succulent-frontend:${{needs.env-job.outputs.modified-branch-name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-backend:
    runs-on: ubuntu-latest
    needs:
      - env-job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gardencmp
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        env:
          branch_name: '${{github.head_ref || github.ref_name}}'
        with:
          context: ./backend
          push: true
          tags: ghcr.io/gardencmp/succulent-backend:${{needs.env-job.outputs.modified-branch-name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-frontend:
    runs-on: ubuntu-latest
    needs:
      - build-frontend
      - env-job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: gacts/install-nomad@v1
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy on Nomad
        env:
          branch_name: '${{github.head_ref || github.ref_name}}'
        run: |
          if [ "${{github.ref_name}}" == "main" ]; then
            export BRANCH_SUFFIX="";
            export BRANCH_SUBDOMAIN="";
          else
            export BRANCH_SUFFIX=-${{needs.env-job.outputs.modified-branch-name}};
            export BRANCH_SUBDOMAIN=${{needs.env-job.outputs.modified-branch-name}}.;
          fi

          export DOCKER_USER=gardencmp;
          export DOCKER_PASSWORD=${{ secrets.DOCKER_PULL_PAT }};
          export DOCKER_TAG=ghcr.io/gardencmp/succulent-frontend:${{needs.env-job.outputs.modified-branch-name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}};

          envsubst '${DOCKER_USER} ${DOCKER_PASSWORD} ${DOCKER_TAG} ${BRANCH_SUFFIX} ${BRANCH_SUBDOMAIN}' < job-template.nomad > job-instance.nomad;
          cat job-instance.nomad;
          NOMAD_ADDR=${{ secrets.NOMAD_ADDR }} nomad job run job-instance.nomad;
        working-directory: ./frontend

  deploy-backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build-backend
      - env-job

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: gacts/install-nomad@v1
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy on Nomad
        env:
          branch_name: '${{github.head_ref || github.ref_name}}'
        run: |
          if [ "${{github.ref_name}}" == "main" ]; then
            export BRANCH_SUFFIX="";
            export BRANCH_SUBDOMAIN="";
          else
            export BRANCH_SUFFIX=-${{needs.env-job.outputs.modified-branch-name}};
            export BRANCH_SUBDOMAIN=${{needs.env-job.outputs.modified-branch-name}}.;
          fi

          export DOCKER_USER=gardencmp;
          export DOCKER_PASSWORD=${{ secrets.DOCKER_PULL_PAT }};
          export DOCKER_TAG=ghcr.io/gardencmp/succulent-backend:${{needs.env-job.outputs.modified-branch-name}}-${{github.sha}}-${{github.run_number}}-${{github.run_attempt}};

          envsubst '${DOCKER_USER} ${DOCKER_PASSWORD} ${DOCKER_TAG} ${BRANCH_SUFFIX} ${BRANCH_SUBDOMAIN}' < job-template.nomad > job-instance.nomad;
          cat job-instance.nomad;
          NOMAD_ADDR=${{ secrets.NOMAD_ADDR }} nomad job run job-instance.nomad;
        working-directory: ./backend
